# Generated by Django 3.2.9 on 2021-12-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(default=0, null=True, verbose_name='Зарплата'),
        ),
    ]
