# Generated by Django 3.2.10 on 2021-12-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vacancy_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя сотрудника')),
                ('job_title', models.CharField(max_length=200, verbose_name='Специальность')),
                ('city', models.CharField(max_length=100, verbose_name='Город проживания')),
                ('expected_salary', models.IntegerField(default=0, null=True, verbose_name='Ожидаемая зарплата')),
                ('job_experience', models.IntegerField(default=0, verbose_name='Опыт работы в месяцах')),
                ('study_degree', models.TextField(null=True, verbose_name='Образование')),
                ('description', models.TextField(null=True, verbose_name='Описание себя')),
            ],
        ),
    ]
