# Generated by Django 3.2.10 on 2021-12-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_resumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='email',
            field=models.CharField(max_length=200, null=True, verbose_name='Email'),
        ),
    ]
